name: tipi.build 
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build: 
    name: build-linux
    runs-on: ubuntu-latest
    container: tipibuild/tipi-ubuntu
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: tipi builds project 
        run: |
          export HOME=/root
          mkdir -p ~/.tipi

          mkdir -p build/linux/bin/demo \
            && curl http://download.hrz.tu-darmstadt.de/media/FB20/GCC/project_files/mapmap/planesweep_320_256_96.bin --output build/linux/bin/demo/planesweep_320_256_96.bin          

          tipi . -t linux --dont-upgrade --verbose --test all 
